/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/app/index.vue')['default']
    AppLayoutsAuth: typeof import('./src/app/layouts/auth.vue')['default']
    AppLayoutsDefault: typeof import('./src/app/layouts/default.vue')['default']
    AppLayoutsSecond: typeof import('./src/app/layouts/second.vue')['default']
    FeaturesLangUiLangSwitcher: typeof import('./src/features/lang/ui/LangSwitcher.vue')['default']
    FeaturesThemeUiThemeSwitcher: typeof import('./src/features/theme/ui/themeSwitcher.vue')['default']
    PagesAbout: typeof import('./src/pages/about/index.vue')['default']
    PagesIndex: typeof import('./src/pages/index/index.vue')['default']
    PagesProfile: typeof import('./src/pages/profile/index.vue')['default']
    PagesProfileEdit: typeof import('./src/pages/profile/edit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedIconsLogo: typeof import('./src/shared/icons/logo.vue')['default']
    SharedUiButton: typeof import('./src/shared/ui/button.vue')['default']
    SharedUiSearch: typeof import('./src/shared/ui/search.vue')['default']
    WidgetsFooter: typeof import('./src/widgets/footer/index.vue')['default']
    WidgetsHeaderUi: typeof import('./src/widgets/header/ui/index.vue')['default']
    WidgetsHeaderUiDesktop: typeof import('./src/widgets/header/ui/desktop.vue')['default']
    WidgetsHeaderUiMobile: typeof import('./src/widgets/header/ui/mobile.vue')['default']
    WidgetsProfile: typeof import('./src/widgets/profile/index.vue')['default']
  }
}
